### PR TITLE
Add ARM64 Support and Optimize Build Process

### PR DESCRIPTION
**Pull request by danielchristianschroeter**
This pull request introduces ARM64 platform support to the MGOB project, enhancing cross-platform compatibility and broadening its usability across diverse architectures. Key updates include:

1. **ARM64 Integration:**
   - Updated Docker configurations to support both `linux/amd64` and `linux/arm64` platforms.
   - Modified the build processes to recognize and correctly handle the ARM64 architecture, ensuring smooth deployment and execution.

2. **Workflow and Build Optimization:**
   - Improved the CI/CD pipeline by updating GitHub workflows for more efficient builds, leveraging newer versions of the action tools for better performance and stability.
   - Refactored scripts (`build.sh`) to dynamically determine architecture and execute conditional installations of dependencies like RClone, MinIO, and cloud SDKs (Azure, AWS, Google Cloud) based on environment variables.
   - Enhanced Dockerfiles to streamline multistage builds and leverage architectural-specific optimizations.

3. **Dependency Updates:**
   - Bumped versions for key dependencies across Dockerfiles for enhanced security and feature improvements. This includes updated versions of Azure CLI, Google Cloud SDK, etc.

4. **Codebase Refactoring:**
   - Cleaned up redundant code and streamlined build scripts for easier maintenance.
   - Adjusted commands and configurations to align with best practices.

5. **Successful Build and Deployment Demonstrations:**
   - Verified the updates with successful build actions:
     - [Dev-build](https://github.com/danielchristianschroeter/mgob/actions/runs/11710808169)
     - [Releases](https://github.com/danielchristianschroeter/mgob/actions/runs/11710269892)
     - [Mongo Tool Build](https://github.com/danielchristianschroeter/mgob/actions/runs/11692784571)
   - Finalized and deployed Docker images, accessible at:
     - [Mongo Tool on Docker Hub](https://hub.docker.com/repository/docker/danielschroeter/mongo-tool/general)
     - [MGOB on Docker Hub](https://hub.docker.com/repository/docker/danielschroeter/mgob/general)

This implementation addresses and resolves [Issue #116](https://github.com/maxisam/mgob/issues/116). Your feedback and suggestions are welcome to further refine MGOB's functionalities and compatibility.

### CODE REVIEW

**Comment by maxisam** [comment]
@danielchristianschroeter Thanks for making this PR, I reverted the docker build in the workflow. It shouldn't push before going through the test.

**Comment by maxisam** [comment]
nvm, there is an issue of load with multi-platform

**Comment by maxisam** [comment]
I just removed ARM docker build before test. But to be honest, if we really wanna ensure it works, we probably should use M1 runner? It will be a bigger change for the workflow I think

**Review by maxisam — APPROVED** [review]

**Comment by danielchristianschroeter** [comment]
> I just removed ARM docker build before test. But to be honest, if we really wanna ensure it works, we probably should use M1 runner? It will be a bigger change for the workflow I think

M1 isn't typically used in server environments, it may not be the optimal solution for our needs. It might be more efficient to utilize existing ARM-compatible CI/CD tools to ensure our builds are properly tested across ARM architecture. This approach could maintain our current workflow with minimal disruption while still achieving reliable testing.

**Pull request merged**
