### PR TITLE
feature: remove `/config` from the Dockerfile VOLUME instruction

### PR DESCRIPTION
**Pull request by sjiep**
Addresses #125

@maxisam you mentioned to let it stay for a week, so feel free to merge whenever you are comfortable. 

Perhaps you could already make a release with dev tag so that I can test it from my side?

### CODE REVIEW

**Comment by maxisam** [comment]
https://github.com/maxisam/mgob/actions/runs/10722607810/job/29748977592 

build doesn't pass with this change

**Comment by sjiep** [comment]
From the logs I can tell why the endpoints are not available and it exits with the following error.

```
curl: (7) Failed to connect to 127.0.0.1 port 8090 after 0 ms: Connection refused
```

In principle, the issue I'm having is that only the config shouldn't be stored in an anonymous volume as this causes rebuilds with different values not to be picked up. Also the config is known at build time and is used for reading only, so having it stored in a volume makes little sense to me and should just be part of the image (or via a bind-mount to host if you don't build an image from it).

I've put the VOLUME instruction back, but only removed the `"/config"` entry. It is hard for me to tell if this will actually fix the build, but can you give it a try?

**Comment by maxisam** [comment]
It works now

**Comment by sjiep** [comment]
I've test with [dev.295](https://hub.docker.com/layers/maxisam/mgob/dev.295/images/sha256-6b60e5123691fccf0d42cd51c3aebaa12f3bc1081a00bf78edd5dce80c8fd165?context=explore)  and can confirm that changes to yaml files in config are not properly picked up after rebuilding a new image from a `Dockfile` with mgob as base image.

**Comment by maxisam** [comment]
@sjiep Thanks for testing. So the new image will use your config properly if you use the public build as a base right?

**Comment by sjiep** [comment]
Sorry, I had a typo in my message the **not** should be **now** 😅.

Just to be sure we are talking about the same thing, with the following `Dockerfile`

```Dockerfile
FROM maxisam/mgob:dev.295

COPY ./gpg/key.gpg.pub /gpg/
COPY ./config/plan.yml /config/
```

Making changes to the `./config/plan.yml` and triggering a new build, `docker compose up --build` in this case`, will cause the changes to be picked up immediately whereas before they weren't.

**Comment by maxisam** [comment]
Cool, that is what I thought. I was a bit confused earlier 😆 I will merge this Friday. Pls remind me if I don't. Thanks!

**Comment by sjiep** [comment]
> Cool, that is what I thought. I was a bit confused earlier 😆 I will merge this Friday. Pls remind me if I don't. Thanks!

As small reminder for merging 😉

**Comment by maxisam** [comment]
Thanks! Completely forgot...I was on a business trip and the flight got cancelled.Totally messed up my plan and forgot about this.

**Comment by sjiep** [comment]
@maxisam, I have still one small favor to ask, could you make a release?

**Comment by maxisam** [comment]
here you go, https://github.com/maxisam/mgob/releases/tag/2.0.24

Thanks for the contribution 😊

**Pull request merged**
