### PR TITLE
Dynamic statefulset replicas value

### PR DESCRIPTION
**Pull request by vissarionas**

### CODE REVIEW

**Comment by maxisam** [comment]
To be honest, I don't know if it will work correctly. I don't think the code handles multiple instances

**Comment by vissarionas** [comment]
I will run more tests and let you know. My usecase for this is that to be used as an on/off switch for backups.

**Comment by maxisam** [comment]
i see. I guess I can merge you change for now and add a property like Enable to schedule, so you can set it any time you want?

**Comment by maxisam** [comment]
if you can add a line of warning in the value file like not supporting more than 1 replica, I think it should be good enough

**Comment by vissarionas** [comment]
We can do better, by creating a jsonSchema validating this replicasCount to not exceed 1 (untill there is the need to higher anyway)
https://helm.sh/docs/topics/charts/#schema-files

I'll update me pr, with some delay.

**Pull request closed without merging**
